[package]
name = "rmedvis"
version = "0.1.0"
authors = ["Stian Soltvedt <stian@soltvedt.info>"]
edition = "2018"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.5.0", features = ["dynamic"] }
