[package]
name = "rmedvis"
version = "0.1.0"
authors = ["Stian Soltvedt <stian@soltvedt.info>"]
edition = "2021"
license = "GPL-3.0-only"
readme = "README.md"
repository = "https://github.com/stisol/rmedvis/"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gl = "0.14.0"
sdl2 = { version = "0.35.1", features = ["bundled", "static-link"] }
anyhow = "1.0.44"
render_gl_derive = { path = "render_gl_derive" }
nalgebra = "0.29.0"
tobj = "3.2.0"
egui = "0.15.0"
notify = "4.0.17"
clipboard = "0.5"
webbrowser = "0.5.5"

[build-dependencies]
walkdir = "2.3.2"
