[package]
name = "rmedvis"
version = "0.1.0"
authors = ["Stian Soltvedt <stian@soltvedt.info>"]
edition = "2018"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-executor = "1.4.1"
bytemuck = { version = "1.5.1", features = ["derive"] }
cgmath = "0.18.0"
color-backtrace = "0.5.1"
env_logger = "0.8.3"
pollster = "0.2"
wgpu = "0.8.1"
winit = "0.25.0"
log = "0.4.14"