[package]
name = "ivrigst"
version = "1.0.0"
authors = ["Stian Soltvedt <stian@soltvedt.info>"]
edition = "2021"
license-file ="LICENSE.md"
readme = "README.md"
repository = "https://github.com/stisol/ivrigst/"
publish = false

[dependencies]
gl = "0.14.0"
sdl2 = { version = "0.35.1", features = ["bundled", "static-link"] }
anyhow = "1.0.52"
render_gl_derive = { path = "render_gl_derive" }
nalgebra = "0.30.1"
tobj = "3.2.1"
egui = "0.16.1"
notify = "4.0.17"
clipboard = "0.5"
webbrowser = "0.5.5"

[build-dependencies]
walkdir = "2.3.2"
