[package]
name = "rmedvis"
version = "0.1.0"
authors = ["Stian Soltvedt <stian@soltvedt.info>"]
edition = "2018"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gl = "0.14.0"
sdl2 = { version = "0.34.5", features = ["bundled", "static-link"] }
anyhow = "1.0.40"

[build-dependencies]
walkdir = "2.3.2"
